#
# Copyright Â© 2016-2020 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: trendz-python-executor-config
  namespace: thingsboard
  labels:
    name: trendz-python-executor-config-label
data:
  requirements.txt: |
    # Mounted by trendz-python-executor-config
    pandas==2.0.3
    numpy==1.24.3
    scikit-learn==1.3.0
    matplotlib==3.7.2
    seaborn==0.12.2
    requests==2.31.0
    pytz==2023.3
    plotly==5.15.0
    statsmodels==0.14.0
    scipy==1.11.1
    joblib==1.3.2

  python-executor.conf: |
    # Mounted by trendz-python-executor-config
    export LOG_FILENAME=python-executor.out
    export LOADER_PATH=/usr/share/python-executor/conf
    
    export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb"
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc=debug:file=/var/log/python-executor/gc.log -XX:+IgnoreUnrecognizedVMOptions -XX:+PrintGCDateStamps"
    export JAVA_OPTS="$JAVA_OPTS -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10"
    export JAVA_OPTS="$JAVA_OPTS -XX:GCLogFileSize=10M -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=10000 -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+CMSParallelInitialMarkEnabled"
    export JAVA_OPTS="$JAVA_OPTS -XX:+CMSEdenChunksRecordAlways -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly"
    
    export JAVA_OPTS="$JAVA_OPTS -Xms1024m -Xmx1024m"
    export JAVA_OPTS="$JAVA_OPTS -XX:MaxMetaspaceSize=128m"
    export JAVA_OPTS="$JAVA_OPTS -XX:MaxDirectMemorySize=128m"
    export JAVA_OPTS="$JAVA_OPTS -XX:+HeapDumpOnOutOfMemoryError"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
    export JAVA_OPTS="$JAVA_OPTS -XX:+AlwaysPreTouch"
    
    export JAVA_OPTS="$JAVA_OPTS -Djava.rmi.server.hostname=0.0.0.0"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.port=8183"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.rmi.port=8183"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
    export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.ssl=false"
    
    # Python Executor Configuration
    # export SCRIPT_ENGINE_RUNTIME_TIMEOUT=10000
    # export EXECUTOR_MANAGER=1
    # export EXECUTOR_SCRIPT_ENGINE=6
    # export THROTTLING_QUEUE_CAPACITY=10
    # export NETWORK_BUFFER_SIZE=20971520

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <!-- Mounted by trendz-python-executor-config -->
    
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">
        
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <Pattern>
                    %green(%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS}) | %highlight(%-5level) [%cyan(%-40thread)] %-60yellow(%C{1}): %msg %n%throwable
                </Pattern>
            </encoder>
        </appender>
        
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
        
        <logger name="org.springframework.web.socket" level="INFO"/>
        <logger name="org.thingsboard.trendz.pythonexecutor" level="DEBUG"/>
        <logger name="org.thingsboard.trendz.pythonexecutor.service.engine.PythonScriptEngine" level="INFO"/>
    
    </configuration>
---
